<?php

/**
 * @file
 * Holds hook implementation for the Message Group Notify module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function message_group_notify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the message_group_notify module.
    case 'help.page.message_group_notify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Notifies groups on entity creation or update.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function message_group_notify_theme() {
  return [
    'message_group_notify' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_insert().
 */
function message_group_notify_entity_insert(EntityInterface $entity) {
  /** @var \Drupal\message_group_notify\EntitySubscriber $subscriber */
  $subscriber = \Drupal::service('message_group_notify.entity_subscriber');
  $subscriber->onCreate($entity);
}

/**
 * Implements hook_entity_update().
 */
function message_group_notify_entity_update(EntityInterface $entity) {
  /** @var \Drupal\message_group_notify\EntitySubscriber $subscriber */
  $subscriber = \Drupal::service('message_group_notify.entity_subscriber');
  $subscriber->onUpdate($entity);
}

/**
 * Implements hook_entity_update().
 */
function message_group_notify_entity_delete(EntityInterface $entity) {
  /** @var \Drupal\message_group_notify\EntitySubscriber $subscriber */
  $subscriber = \Drupal::service('message_group_notify.entity_subscriber');
  $subscriber->onDelete($entity);
}
